#!/usr/bin/env sh

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding
# yabai -m config top_padding 26
# yabai -m config top_padding 6
yabai -m config bottom_padding 0
yabai -m config left_padding 6
yabai -m config right_padding 6
yabai -m config window_gap 4

# add 20 padding to the top and bottom of all spaces regardless of the display it belongs to
yabai -m config external_bar all:44:3

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse autoraise

# center mouse on window with focus
yabai -m config mouse_follows_focus on

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap

apps_to_ignore="(System Settings|Calculator|Karabiner-Elements|licecap|Preview|Calendar|licecap)"
yabai -m rule --add app="Godot$" manage=off
yabai -m rule --add app="${apps_to_ignore}" manage=off
# yabai -m rule --add app="^Calculator$" manage=off
# yabai -m rule --add app="^Karabiner-Elements$" manage=off
# yabai -m rule --add app="^licecap$" manage=off

# Make the below apps transparent
yabai -m config window_opacity off
apps_transparent="(Cursor|Sublime Text)"
# yabai -m signal --add event=window_focused app="^${apps_transparent}$" action="yabai -m config active_window_opacity 0.8"
# yabai -m signal --add event=window_focused app="^${apps_transparent}$" action="yabai -m config normal_window_opacity 0.8"

# When any other app gains focus, reset both active and background window opacity to fully visible
# yabai -m signal --add event=window_focused app!="^${apps_transparent}$" action="yabai -m config active_window_opacity 1.0"
# yabai -m signal --add event=window_focused app!="^${apps_transparent}$" action="yabai -m config normal_window_opacity 1.0"


# Active windown border
borders active_color=0xff7ed6df inactive_color=0xff494d64 width=3.0 &

# yabai -m config menubar_opacity 0.0

sudo yabai --load-sa
