#!/usr/bin/env sh

# change window focus within space
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - h : yabai -m window --focus west
alt - l : yabai -m window --focus east

#change focus between external displays (left and right)
alt - s: yabai -m display --focus west
alt - g: yabai -m display --focus east

# rotate layout clockwise
shift + alt - r : yabai -m space --rotate 270

# flip along y-axis
shift + alt - y : yabai -m space --mirror y-axis

# flip along x-axis
shift + alt - x : yabai -m space --mirror x-axis

# toggle window float
shift + alt - t : yabai -m window --toggle float --grid 10:15:1:1:13:8

# maximize a window
shift + alt - m : yabai -m window --toggle zoom-fullscreen

# balance out tree of windows (resize to occupy same area)
shift + alt - e : yabai -m space --balance

# swap windows
shift + alt - j : yabai -m window --swap south
shift + alt - k : yabai -m window --swap north
shift + alt - h : yabai -m window --swap west
shift + alt - l : yabai -m window --swap east

# move window and split
ctrl + alt - j : yabai -m window --swap west || (yabai -m window --display west; yabai -m display --focus west)
ctrl + alt - k : yabai -m window --swap south || (yabai -m window --display south; yabai -m display --focus south)
ctrl + alt - h : yabai -m window --swap north || (yabai -m window --display north; yabai -m display --focus north)
ctrl + alt - l : yabai -m window --swap east || (yabai -m window --display east; yabai -m display --focus east)

# move window to display left and right
shift + alt - s : yabai -m window --display west; yabai -m display --focus west
shift + alt - g : yabai -m window --display east; yabai -m display --focus east

#move window to prev and next space
# shift + alt - p : yabai -m window --space prev;
# shift + alt - n : yabai -m window --space next;

# move window to space #
shift + alt - 1 : yabai -m window --space 1
shift + alt - 2 : yabai -m window --space 2
shift + alt - 3 : yabai -m window --space 3
shift + alt - 4 : yabai -m window --space 4
shift + alt - 5 : yabai -m window --space 5
shift + alt - 6 : yabai -m window --space 6
shift + alt - 7 : yabai -m window --space 7

# Switch space
alt + ctrl - 1: yabai -m space --focus 1
alt + ctrl - 2: yabai -m space --focus 2
alt + ctrl - 3: yabai -m space --focus 3
alt + ctrl - 4: yabai -m space --focus 4
alt + ctrl - 5: yabai -m space --focus 5
alt + ctrl - 6: yabai -m space --focus 6
alt + ctrl - 7: yabai -m space --focus 7
alt + ctrl - 8: yabai -m space --focus 8

alt + cmd - 1: yabai -m space --focus 1
alt + cmd - 2: yabai -m space --focus 2
alt + cmd - 3: yabai -m space --focus 3
alt + cmd - 4: yabai -m space --focus 4
alt + cmd - 5: yabai -m space --focus 5
alt + cmd - 6: yabai -m space --focus 6
alt + cmd - 7: yabai -m space --focus 7
alt + cmd - 8: yabai -m space --focus 8

alt + cmd + ctrl - 1: yabai -m space --focus 1
alt + cmd + ctrl - 2: yabai -m space --focus 2
alt + cmd + ctrl - 3: yabai -m space --focus 3
alt + cmd + ctrl - 4: yabai -m space --focus 4
alt + cmd + ctrl - 5: yabai -m space --focus 5
alt + cmd + ctrl - 6: yabai -m space --focus 6
alt + cmd + ctrl - 7: yabai -m space --focus 7
alt + cmd + ctrl - 8: yabai -m space --focus 8


ctrl - right: yabai -m space --focus next || yabai -m space --focus first
ctrl - left: yabai -m space --focus prev || yabai -m space --focus last

ctrl + alt + cmd - l: yabai -m space --focus next || yabai -m space --focus first
ctrl + alt + cmd - h: yabai -m space --focus prev || yabai -m space --focus last

shift - backspace: yabai -m space --focus recent
# shift - capslock: yabai -m space --focus recent

# stop/start/restart yabai
ctrl + alt - q : yabai --stop-service
ctrl + alt - s : yabai --start-service
cmd + alt - r : yabai --restart-service

# Focus window
alt + ctrl - h : yabai -m window --swap west || (yabai -m window --display west; yabai -m display --focus west)
alt + ctrl - j : yabai -m window --swap south || (yabai -m window --display south; yabai -m display --focus south)
alt + ctrl - k : yabai -m window --swap north || (yabai -m window --display north; yabai -m display --focus north)
alt + ctrl - l : yabai -m window --swap east || (yabai -m window --display east; yabai -m display --focus east)

# resize windows
ctrl + cmd - h : yabai -m window west --resize right:-20:0 2> /dev/null || yabai -m window --resize right:-20:0
ctrl + cmd - j : yabai -m window north --resize bottom:0:20 2> /dev/null || yabai -m window --resize bottom:0:20
ctrl + cmd - k : yabai -m window south --resize top:0:-20 2> /dev/null || yabai -m window --resize top:0:-20
ctrl + cmd - l : yabai -m window east --resize left:20:0 2> /dev/null || yabai -m window --resize left:20:0

# Color filters
alt + ctrl - backspace: shortcuts run "Toggle Color Filters"
alt + ctrl + cmd - n: shortcuts run "Set Night Shift"

cmd + alt - n : yabai -m space --create
cmd + alt - w : yabai -m space --destroy
